# ===================================
#  List Behavior Config
# ===================================

title: tiipiik.catalog::lang.config.list.title
list: ~/plugins/tiipiik/catalog/models/category/columns.yaml
modelClass: Tiipiik\Catalog\Models\Category
recordUrl: tiipiik/catalog/categories/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
showSorting: true
showTree: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
