# ===================================
#  Form Behavior Config
# ===================================

name: Brand
form: $/tiipiik/catalog/models/brand/fields.yaml
modelClass: Tiipiik\Catalog\Models\Brand
defaultRedirect: tiipiik/catalog/brands
create:
    title: Create Brand
    redirect: tiipiik/catalog/brands/update/:id
    redirectClose: tiipiik/catalog/brands
update:
    title: Edit Brand
    redirect: tiipiik/catalog/brands
    redirectClose: tiipiik/catalog/brands