# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Brand

# Model Form Field configuration
form: $/tiipiik/catalog/models/brand/fields.yaml

# Model Class name
modelClass: Tiipiik\Catalog\Models\Brand

# Default redirect location
defaultRedirect: tiipiik/catalog/brands

# Create page
create:
    title: Create Brand
    redirect: tiipiik/catalog/brands/update/:id
    redirectClose: tiipiik/catalog/brands

# Update page
update:
    title: Edit Brand
    redirect: tiipiik/catalog/brands
    redirectClose: tiipiik/catalog/brands

# Preview page
preview:
    title: Preview Brand