# ===================================
# Filter Scope Definitions
# ===================================
scopes:

    category:

        # Filter name
        label: tiipiik.catalog::lang.products.category

        # Model Class name
        modelClass: Tiipiik\Catalog\Models\Category

        # Model attribute to display for the name
        nameFrom: name

        # Apply query scope
        scope: FilterCategories