# ===================================
#  Form Behavior Config
# ===================================

name: CustomValue
form: $/tiipiik/catalog/models/customvalue/fields.yaml
modelClass: Tiipiik\Catalog\Models\CustomValue
defaultRedirect: tiipiik/catalog/customvalues
showCheckboxes: false
#create:
#    title: Create CustomValue
#    redirect: tiipiik/catalog/customvalues/update/:id
#    redirectClose: tiipiik/catalog/customvalues
update:
    title: Edit CustomValue
    redirect: tiipiik/catalog/customvalues
    redirectClose: tiipiik/catalog/customvalues