# ===================================
#  List Behavior Config
# ===================================

title: tiipiik.catalog::lang.config.list.customvalue_title
list: ~/plugins/tiipiik/catalog/models/customvalue/columns.yaml
modelClass: Tiipiik\Catalog\Models\CustomValue
recordUrl: tiipiik/catalog/customvalues/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSorting: true
