# ===================================
#  List Behavior Config
# ===================================

title: Manage CustomFields
list: $/tiipiik/catalog/models/customfield/columns.yaml
modelClass: Tiipiik\Catalog\Models\CustomField
recordUrl: tiipiik/catalog/customfields/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
showSorting: true
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
