# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: CustomField

# Model Form Field configuration
form: $/tiipiik/catalog/models/customfield/fields.yaml

# Model Class name
modelClass: Tiipiik\Catalog\Models\CustomField

# Default redirect location
defaultRedirect: tiipiik/catalog/customfields

# Create page
create:
    title: Create CustomFields
    redirect: tiipiik/catalog/customfields/update/:id
    redirectClose: tiipiik/catalog/customfields

# Update page
update:
    title: Edit CustomFields
    redirect: tiipiik/catalog/customfields
    redirectClose: tiipiik/catalog/customfields

# Preview page
preview:
    title: Preview CustomFields